-- Check admin1 password
SELECT USER_ID, USERNAME, PASSWORD, EMAIL, ROLE
FROM USERS
WHERE USERNAME = 'admin1';

-- Check all admin accounts
SELECT USER_ID, USERNAME, PASSWORD, EMAIL, ROLE
FROM USERS
WHERE ROLE = 'ADMIN';